services:
    db:
      image: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com/zhama-ai/postgres:17.1-alpine
      restart: always
        #ports:
        #- 5432:5432
      volumes:
        - ./volumes/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=1
        - POSTGRES_USER=conductor
        - POSTGRES_DB=conductor
      healthcheck:
        test: ['CMD', 'pg_isready', '-U', 'grasp']
        interval: 30s
        timeout: 30s
        retries: 3
    conductor-mcp-server:
      image: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com/zhama-ai/conductor-mcp-server:v1.0.0
      environment:
        - DEBUG=False
        - TCARE_SERVER=http://tcare-mock-server:4000
      volumes:
        - ./volumes/mcp-server/logs:/app/logs
    conductor-server:
      image: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com/zhama-ai/conductor-server:v1.0.0
      restart: always
      ports:
        - 15000:9000
      volumes:
        - ./volumes/conductor-server/logs:/server/logs
        - ./volumes/conductor-server/data:/server/data
          #- ./grasp-server:/server
      depends_on:
        - db
        - redis
        - conductor-mcp-server
      environment:
        - APP_NAME=ConductorServer
        - DEBUG=False
        - ENVIRONMENT=production
        - API_PREFIX=/api/v1
        - DATABASE_URL=postgresql+asyncpg://conductor:1@db:5432/conductor
        - DATABASE_POOL_SIZE=100
        - DATABASE_MAX_OVERFLOW=1000
        - DATABASE_POOL_TIMEOUT=30
        - SECRET_KEY=1
        - ACCESS_TOKEN_EXPIRE_MINUTES=30
        - ALGORITHM=HS256
        - LOG_LEVEL=ERROR
        - MACAROONS_SECRETKEY=1
        - MACAROONS_LOCATION=api.zhama.com.cn
        - MACAROONS_IDENTIFIER=zhama
        - REDIS_HOST=redis
        - RELOAD=False
        - WORKERS=4
        - SMS_MOCK=True
        - TCARE_SERVER=http://tcare-mock-server:3000
        - LLM_SERVER=https://one.zhama.com.cn/v1
        - LLM_KEY=1111
        - LLM_MODEL=google/gemini-2.5-flash-preview
        - TCARE_MCP_SERVER_URL=http://conductor-mcp-server:23000/sse
    conductor-web:
      image: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com/zhama-ai/conductor-web:v1.0.0
      restart: always
      ports:
        - 40000:3000
      volumes:
        - ./volumes/conductor-web/logs:/app/logs
      depends_on:
        - conductor-server
        - db
      environment:
        - BACKEND_URL=http://conductor-server:9000
        - DASHSCOPE_API_KEY=1234567890
        - NEXT_PUBLIC_VOICE_PROVIDER=aliyun
    tcare-mock-server:
      image: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com/zhama-ai/tcare-mock-server:v1.0.0
      restart: always
      volumes:
        - ./volumes/tcare-mock-server/logs:/app/logs
    redis:
      image: crpi-zcgiub6jx8rljw6m.cn-hangzhou.personal.cr.aliyuncs.com/zhama-ai/redis:6.2
      restart: always